apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackazon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackazon
  template:
    metadata:
      labels:
        app: hackazon
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: hackazon
        image: icompman/hackazon
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hackazon
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hackazon
